pipeline {
    agent any
    tools {
    maven 'maven'
}
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
        post {
        always {
            archiveArtifacts artifacts: '*.jar', onlyIfSuccessful: true
    }
    }
}
