pipeline {
    agent any
    tools {
    maven 'maven'
}
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                archiveArtifacts artifacts: '*.jar'
            }
        }
    }
}
